# Generated by Django 5.0.2 on 2025-06-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='Admin', max_length=100)),
                ('admin_title', models.CharField(blank=True, help_text='Jabatan atau deskripsi singkat', max_length=100, null=True)),
                ('admin_photo', models.ImageField(blank=True, null=True, upload_to='admin/')),
                ('admin_description', models.TextField(blank=True, null=True)),
                ('footer_text', models.CharField(default='© 2023 Bio Link. All rights reserved.', max_length=255)),
                ('footer_show_social', models.BooleanField(default=True, help_text='Tampilkan ikon media sosial di footer')),
                ('site_title', models.CharField(default='Bio Link', max_length=100)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('site_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='gradient_color',
            field=models.CharField(blank=True, help_text='Warna kedua untuk gradasi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='gradient_direction',
            field=models.CharField(choices=[('to right', 'Kanan'), ('to left', 'Kiri'), ('to bottom', 'Bawah'), ('to top', 'Atas'), ('to bottom right', 'Kanan Bawah'), ('to bottom left', 'Kiri Bawah'), ('to top right', 'Kanan Atas'), ('to top left', 'Kiri Atas')], default='to right', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='gradient_type',
            field=models.CharField(choices=[('linear', 'Linear Gradient'), ('radial', 'Radial Gradient')], default='linear', max_length=20),
        ),
    ]
