# Generated by Django 5.0.2 on 2025-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_whatsapp',
            field=models.CharField(blank=True, help_text='Nomor WhatsApp (format: 628xxxxxxxxxx)', max_length=20, null=True),
        ),
    ]
