# Generated by Django 5.0.2 on 2025-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_admin_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='description',
            field=models.TextField(blank=True, help_text='Keterangan tambahan untuk media sosial', null=True),
        ),
    ]
