# Generated by Django 5.0.2 on 2025-06-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_socialmedia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, help_text='Link untuk layanan ini', null=True),
        ),
    ]
