# Generated by Django 5.0.2 on 2025-06-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_link'),
    ]

    operations = [
    ]
