# Generated by Django 5.0.2 on 2025-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_link_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_label',
            field=models.CharField(default='Link Produk', help_text='Label untuk link produk (misalnya: Link Demo, Link Lainnya)', max_length=50),
        ),
    ]
