# Generated by Django 5.0.2 on 2025-06-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_link_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_link',
            field=models.URLField(blank=True, help_text='Link tambahan untuk produk', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_link_label',
            field=models.CharField(blank=True, default='Link Lainnya', help_text='Label untuk link tambahan', max_length=50, null=True),
        ),
    ]
