# Generated by Django 5.0.2 on 2025-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('saweria', 'Saweria'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('twitch', 'Twitch'), ('reddit', 'Reddit'), ('medium', 'Medium'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('website', 'Website'), ('other', 'Other')], max_length=30),
        ),
    ]
